var names = {   // borrowed idea from liri

    var animalNames: { 
        
        'bird' 
        'fish' 
        'monkey' 
        'tiger' 
        'iguana' 
        'lion' 
        'chimp' 
        'badger' 
        'penguin' 
        'owl' 
        'bear' 
        'bulldog' 
        'rhinoceros' 
        'spider' 
        'antelope' 
        'butterfly'
        'catfish' 
        'cheetah' 
        'dolphin'
        'duck' 
        'coyote' 
        'squirrel' 
        'gorilla' 
        'leopard' 
        'lobstercatfish' 
        'cheetah' 
        'dolphin'
        'duck' 
        'coyote' 
        'squirrel' 
        'gorilla' 
        'leopard' 
        'lobstercatfish' 
        'cheetah' 
        'dolphin'
        'duck' 
        'coyote' 
        'squirrel' 
        'gorilla' 
        'leopard' 
        'lobstercatfish' 
        'cheetah' 
        'dolphin'
        'duck' 
        'coyote' 
        'squirrel' 
        'gorilla' 
        'leopard' 
        'lobstercatfish' 
        'cheetah' 
        'dolphin'
        'duck' 
        'coyote' 
        'squirrel' 
        'gorilla' 
        'leopard' 
        'lobster'

    }
}

module.exports.names